development:
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  database: dummy_api_dev

vagrant:
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  database: dummy_api_vagrant

test:
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  database: dummy_api_test

production:
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  database: dummy_api_prod