---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: default
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: default
  image_type: 
  image_id: 
  security_groups:
  - default
  - web
  external_host: 
  external_ip: 192.168.70.10
  internal_host: 
  internal_ip: 192.168.70.10
  zone: 
  provider: vagrant
  platform: linux
  root_device_type: 
- volumes: {}
  static_ips: {}
